trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

variables:
- group: sonarqube

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: '--build-arg SONAR_VERSION=8.7.1.42226'
        containerRegistry: 'Docker Hub'
        repository: 'leandromoreirajfa'
        tags: |
          $(tag)