trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

variables:
- group: sonarqube
- group: general

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build and Push Image
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: $(DockerfilePath)
        arguments: --build-arg SONAR_VERSION=$(sonarqube_version)
        containerRegistry: $(imageRegistry)
        repository: $(sonarqube_repository)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push Image
      inputs:
        command: push
        containerRegistry: $(imageRegistry)
        repository: $(sonarqube_repository)
        tags: |
          $(tag)