# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

variables:
- group: sonarqube

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build and Push Image
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: buildandPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: '--build-arg SONAR_VERSION=$(sonarqube_version)'
        containerRegistry: 'docker_hub'
        repository: $(repostory_sonarqube)
        tags: |
          $(tag)