# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

name: 
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: '--build-arg SONAR_VERSION=8.7.1.42226'
        containerRegistry: 'Docker Hub'
        repository: 'leandromoreirajfa'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)