trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

variables:
- group: sonarqube
- group: general

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build and Push Image
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: $(DockerfilePath)
        arguments: --build-arg SONAR_VERSION=8.7.1.42226
        containerRegistry: 'docker_hub'
        repository: $(sonarqube_repostory)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push Image
      inputs:
        command: push
        containerRegistry: $(registry)
        repository: $(repository_sonarqube)
        tags: |
          $(tag)