# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

name: 
variables:
- group: sonarqube

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: '--build-arg SONAR_VERSION=8.7.1.42226'
        containerRegistry: 'Docker Hub'
        repository: 'leandromoreirajfa'
        tags: |
          $(tag)
        
    - task: Docker@2
      displayName: Push Image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'leandromoreirajfa'
        command: 'Push'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)